name: "Package and release gem"
on:
  workflow_dispatch:

jobs:
  release:
    environment: release
    permissions:
      id-token: write
      contents: read
    timeout-minutes: 5
    name: "Release on RubyGems"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # v5.0.1
      - name: "Setup Ruby"
        uses: ruby/setup-ruby@90be1154f987f4dc0fe0dd0feedac9e473aa4ba8 # v1.286.0
        with:
          ruby-version: "3.4.8"
          bundler-cache: true
      - name: Publish to RubyGems
        uses: rubygems/release-gem@1c162a739e8b4cb21a676e97b087e8268d8fc40b # v1.1.2
